Use QString::toLatin1 instead of obsolete toAscii
This fixes the following build error with Qt 5.4.2:

> openhantek/openhantek/src/helper.h: In function ‘void Helper::timestampDebug(QString)’:
> openhantek/openhantek/src/helper.h:80:66: error: ‘class QString’ has no member named ‘toAscii’
>    qDebug("%s: %s", QTime::currentTime().toString("hh:mm:ss.zzz").toAscii().constData(), text.toAscii().constData());
>                                                                   ^
> openhantek/openhantek/src/helper.h:80:94: error: ‘class QString’ has no member named ‘toAscii’
>    qDebug("%s: %s", QTime::currentTime().toString("hh:mm:ss.zzz").toAscii().constData(), text.toAscii().constData());

According to [1] QString::toAscii was the same as QString::toLatin1.

[1]: https://doc.qt.io/qt-5/qstring-obsolete.html#toAscii